name: Deploy to Dev Environment

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_service:
    name: Redeploy projects-aayush dev Environment
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH & Deploy
        run: |
          SECRET="${{ secrets.SSH_PRIVATE_KEY }}"

          echo "$SECRET" | base64 -d > ~/ssh_key
          chmod 600 ~/ssh_key

          echo "Key file created:"
          ls -l ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@100.52.152.26 << 'EOF'
          cd projects-aayush-joshi/
          git pull
          npm install
          npm run build
          pm2 restart projects-aayush-repo
          EOF
